#!/bin/bash -e

NAME=obb-frontend

NODE_ENV=production time node ./node_modules/browserify/bin/cmd.js . | \
    ./node_modules/uglify-js/bin/uglifyjs -cm > dist/$NAME.min.js

time compass compile -e production --force \
        --sass-dir=css/scss/ --css-dir=dist --images-dir=public/

mv dist/$NAME.css dist/$NAME.min.css

time /usr/local/bin/pngquant --force --ext .png public/*.png
